### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [DevExpress/devextreme-vue#101]
### Issue Type
Question

### Description
How to translate using webpack and vuejs?

I tried using this [https://github.com/DevExpress/devextreme-examples/blob/18_1/webpack-angular-globalize/webpack.config.js](https://github.com/DevExpress/devextreme-examples/blob/18_1/webpack-angular-globalize/webpack.config.js) but doesn't work, do you have example?

**Comment by lukyanovas** [comment]
Hi!
Please take a look at [this issue in our SC](https://www.devexpress.com/Support/Center/Question/Details/T635646).

**Comment by farnetani** [comment]
Last year I did not renew my license because you did not have Vuejs support. I have had several difficulties working with translation (pt-br), but I have seen that in this link has some relevant information that I am needing so that it may be feasible to buy the product again. Is it possible to make PUBLIC the content of this link, considering the relevance of its use?

**Comment by lukyanovas** [comment]
Оh.. Sorry, I've attached project from this ticket here.
[T635646.zip](https://github.com/DevExpress/devextreme-vue/files/2103898/T635646.zip)

**Comment by farnetani** [comment]
Thanks a lot!!!
