### ISSUE TITLE
How do I validate dxTextBox on lost focus?

### ISSUE THREAD

**Issue by botura** [DevExpress/devextreme-vue#103]
### Issue Type
question

### Description
How can I get the same behavior as this? [T596346 - How do I validate dxTextBox on lost focus?](https://www.devexpress.com/Support/Center/Question/Details/T596346/how-do-i-validate-dxtextbox-on-lost-focus)

#### Steps to Reproduce
I've tried this code without success.
```
<template>
	<div>
		<dx-text-box valueChangeEvent="focusout">
			<dx-validator :validationRules="rules" />
		</dx-text-box>
	</div>
</template>

<script>
import { DxTextBox, DxValidator } from 'devextreme-vue';
export default {
	components: {
		DxTextBox,
		DxValidator
	},

	data: function() {
		return {
			rules: [
				{
					type: 'required',
					message: 'this is required'
				}
			]
		};
	}
};
</script>

```

### Environment Details
    "devextreme": "18.1.4-pre-18164",
    "devextreme-vue": "^18.1.4-alpha.5",

**Comment by lukyanovas** [comment]
To get the desired behavior additionally set the `value` option to `null` in your textbox.
See this [example](https://codesandbox.io/s/llox4l7ylm)

This question relates to how our DevExtreme widgets work rather than to our Vue integration. So, if you need a further assistance, please post a question to our [support center](www.devexpress.com/ask).
