### ISSUE TITLE
Autocomplete deadlock

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#188]
### Issue Type
bug report

### Description
When searchExpr bind array, after selection changed script deadlock.

#### Steps to Reproduce
1. Add dx-date-box and bind to data property
2. Add dx-autocomplete
3. Set dataSource
4. Set binding to searchExp to array (e.g. :searchExp="['field']"). If bind to property, no problem.
5. Subscribe on selectionChanged
6. In event handler change property binded to dx-date-box
7. Input value to autocomplete

### Environment Details

"devextreme": "18.1.7-pre-18291",
"devextreme-vue": "18.1.7-alpha.10"
- vue version: 2.5.7

**Comment by lukyanovas** [comment]
Hi!
Hm, I can't reproduce. Could you please to modify [this sample](https://codesandbox.io/s/j72zlkrvk9) to show me the issue?

**Comment by genusP** [comment]
In your sample input 'j' into autocomplete and select first suggestion.

**Comment by IlyaKhD** [comment]
Hi,
> type 'j' into autocomplete and select first suggestion.

I've tried this, and it works fine.

@genusP,
Could you check if the issue can be still reproduced with that example and update it if not?

I would recommend checking your templates for non-constant literals (arrays, objects, dates). Such values are considered as new on every page rendering. This can result in calling event handlers, and if some watched value is modified, the component will be re-rendered and handlers will be called again. All this will result in an infinite loop.

**Comment by genusP** [comment]
Yes I forgot that  example has be updated
https://codesandbox.io/s/n47q21pn0l

**Comment by IlyaKhD** [comment]
After the Autocomplete value is changed:
 
1. The selectionChanged is fired
1. `this.date` is changed, which makes Vue render the template
1. Vue detects that the `:search-expr` value has a new value (since the array is created on each render) and notifies the Autocomplete widget about it
1. The Autocomplete widget fires selectionChanged,
1. Go to step 1
 

To overcome the problem, make the `search-expr` option value constant (move it to `data`)
Here is the updated codesandbox: https://codesandbox.io/s/5vpol0x9p
 
If you have any questions about the Autocomplete widget behavior use the DevExpress Support Center: https://www.devexpress.com/Support/Center
