### ISSUE TITLE
Is not possible handle form items using `ref`

### ISSUE THREAD

**Issue by leandrogehlen** [DevExpress/devextreme-vue#434]
Form items is `undefined` using `ref`

https://codesandbox.io/s/undefined-form-items-5vez6

**Comment by ducmerida** [comment]
I think that you need to use instance and options in order to get the items list, this is the way to get any option according to [DevExtreme documentation](https://js.devexpress.com/Documentation/Guide/jQuery_Components/Component_Configuration_Syntax/#Get_and_Set_Options/Get_a_Single_Option)
https://codesandbox.io/s/aged-leftpad-4xtum?file=/src/components/HelloWorld.vue:842-891

**Comment by leandrogehlen** [comment]
@ducmerida, you are right.
I guess, this issue must be present in documentation
